sudo: false
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-4.0
    packages:
    - gcc-5.4
    - g++-5.4
    - clang-4.0

os:
  - linux
compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test

dist: xenial
notifications:
  email: false